# Generated by Django 4.2 on 2023-06-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactItem',
            fields=[
                ('inid', models.AutoField(primary_key=True, serialize=False)),
                ('tcrd', models.DateTimeField(null=True)),
                ('tmod', models.DateTimeField(null=True)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('irln', models.CharField(blank=True, max_length=128)),
                ('nick', models.CharField(blank=True, max_length=128)),
                ('loca', models.TextField(blank=True, null=True)),
                ('dtmt', models.CharField(blank=True, max_length=64)),
                ('mtth', models.CharField(blank=True, max_length=64)),
                ('seen', models.CharField(blank=True, max_length=32)),
                ('appe', models.TextField(blank=True, null=True)),
                ('smp1', models.CharField(blank=True, choices=[('', ''), ('disc', 'Discord'), ('ebay', 'eBay'), ('epic', 'Epic Games'), ('face', 'Facebook'), ('gith', 'GitHub'), ('link', 'LinkedIn'), ('payp', 'PayPal'), ('inst', 'Instagram'), ('redd', 'Reddit'), ('snap', 'Snapchat'), ('stea', 'Steam'), ('twit', 'Twitter'), ('webs', 'Personal Website')], max_length=128)),
                ('smu1', models.CharField(blank=True, max_length=64)),
                ('smp2', models.CharField(blank=True, choices=[('', ''), ('disc', 'Discord'), ('ebay', 'eBay'), ('epic', 'Epic Games'), ('face', 'Facebook'), ('gith', 'GitHub'), ('link', 'LinkedIn'), ('payp', 'PayPal'), ('inst', 'Instagram'), ('redd', 'Reddit'), ('snap', 'Snapchat'), ('stea', 'Steam'), ('twit', 'Twitter'), ('webs', 'Personal Website')], max_length=128)),
                ('smu2', models.CharField(blank=True, max_length=64)),
                ('smp3', models.CharField(blank=True, choices=[('', ''), ('disc', 'Discord'), ('ebay', 'eBay'), ('epic', 'Epic Games'), ('face', 'Facebook'), ('gith', 'GitHub'), ('link', 'LinkedIn'), ('payp', 'PayPal'), ('inst', 'Instagram'), ('redd', 'Reddit'), ('snap', 'Snapchat'), ('stea', 'Steam'), ('twit', 'Twitter'), ('webs', 'Personal Website')], max_length=128)),
                ('smu3', models.CharField(blank=True, max_length=64)),
                ('smp4', models.CharField(blank=True, choices=[('', ''), ('disc', 'Discord'), ('ebay', 'eBay'), ('epic', 'Epic Games'), ('face', 'Facebook'), ('gith', 'GitHub'), ('link', 'LinkedIn'), ('payp', 'PayPal'), ('inst', 'Instagram'), ('redd', 'Reddit'), ('snap', 'Snapchat'), ('stea', 'Steam'), ('twit', 'Twitter'), ('webs', 'Personal Website')], max_length=128)),
                ('smu4', models.CharField(blank=True, max_length=64)),
                ('smp5', models.CharField(blank=True, choices=[('', ''), ('disc', 'Discord'), ('ebay', 'eBay'), ('epic', 'Epic Games'), ('face', 'Facebook'), ('gith', 'GitHub'), ('link', 'LinkedIn'), ('payp', 'PayPal'), ('inst', 'Instagram'), ('redd', 'Reddit'), ('snap', 'Snapchat'), ('stea', 'Steam'), ('twit', 'Twitter'), ('webs', 'Personal Website')], max_length=128)),
                ('smu5', models.CharField(blank=True, max_length=64)),
                ('smp6', models.CharField(blank=True, choices=[('', ''), ('disc', 'Discord'), ('ebay', 'eBay'), ('epic', 'Epic Games'), ('face', 'Facebook'), ('gith', 'GitHub'), ('link', 'LinkedIn'), ('payp', 'PayPal'), ('inst', 'Instagram'), ('redd', 'Reddit'), ('snap', 'Snapchat'), ('stea', 'Steam'), ('twit', 'Twitter'), ('webs', 'Personal Website')], max_length=128)),
                ('smu6', models.CharField(blank=True, max_length=64)),
                ('ema1', models.CharField(blank=True, max_length=64)),
                ('ema2', models.CharField(blank=True, max_length=64)),
                ('ema3', models.CharField(blank=True, max_length=64)),
                ('ema4', models.CharField(blank=True, max_length=64)),
                ('nphn', models.CharField(blank=True, max_length=32)),
                ('empl', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Entries',
            },
        ),
    ]
