# Generated by Django 4.0.10 on 2023-06-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactItem',
            fields=[
                ('inid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('irln', models.TextField(blank=True)),
                ('loca', models.TextField(blank=True)),
                ('smp1', models.CharField(choices=[('', ''), ('ebay', 'eBay'), ('disc', 'Discord'), ('face', 'Facebook'), ('inst', 'Instagram'), ('snap', 'Snapchat'), ('stea', 'Steam'), ('webs', 'Website')], max_length=128)),
                ('smu1', models.TextField(blank=True)),
                ('smp2', models.CharField(choices=[('', ''), ('ebay', 'eBay'), ('disc', 'Discord'), ('face', 'Facebook'), ('inst', 'Instagram'), ('snap', 'Snapchat'), ('stea', 'Steam'), ('webs', 'Website')], max_length=128)),
                ('smu2', models.TextField(blank=True)),
                ('smp3', models.CharField(choices=[('', ''), ('ebay', 'eBay'), ('disc', 'Discord'), ('face', 'Facebook'), ('inst', 'Instagram'), ('snap', 'Snapchat'), ('stea', 'Steam'), ('webs', 'Website')], max_length=128)),
                ('smu3', models.TextField(blank=True)),
                ('smp4', models.CharField(choices=[('', ''), ('ebay', 'eBay'), ('disc', 'Discord'), ('face', 'Facebook'), ('inst', 'Instagram'), ('snap', 'Snapchat'), ('stea', 'Steam'), ('webs', 'Website')], max_length=128)),
                ('smu4', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Entrties',
            },
        ),
    ]
