# Generated by Django 4.0.10 on 2023-06-10 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactitem',
            options={'verbose_name_plural': 'Contact Entries'},
        ),
    ]
