# Generated by Django 4.0.10 on 2023-06-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactlist', '0002_alter_contactitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactitem',
            name='nte',
            field=models.TextField(blank=True),
        ),
    ]
