# Generated by Django 4.0.10 on 2023-06-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactlist', '0003_contactitem_nte'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactitem',
            name='crd',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='contactitem',
            name='mod',
            field=models.DateTimeField(null=True),
        ),
    ]
