# Generated by Django 4.2.2 on 2023-06-14 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactlist', '0004_contactitem_crd_contactitem_mod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactItem',
        ),
    ]
