# Generated by Django 4.2.2 on 2023-06-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactlist', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactitem',
            name='dmt',
            field=models.DateField(null=True),
        ),
    ]
