# ContactList - CTCL 2023
# Generated: June 15, 2023
# Purpose: Dropdown choices
# THIS FILE IS AUTOMATICALLY GENERATED

choices_smp1 = [
    ("", ""),
    ("ebay", "eBay"),
    ("disc", "Discord"),
    ("face", "Facebook"),
    ("inst", "Instagram"),
    ("snap", "Snapchat"),
    ("stea", "Steam"),
    ("webs", "Website"),
]

choices_smp2 = [
    ("", ""),
    ("ebay", "eBay"),
    ("disc", "Discord"),
    ("face", "Facebook"),
    ("inst", "Instagram"),
    ("snap", "Snapchat"),
    ("stea", "Steam"),
    ("webs", "Website"),
]

choices_smp3 = [
    ("", ""),
    ("ebay", "eBay"),
    ("disc", "Discord"),
    ("face", "Facebook"),
    ("inst", "Instagram"),
    ("snap", "Snapchat"),
    ("stea", "Steam"),
    ("webs", "Website"),
]

choices_smp4 = [
    ("", ""),
    ("ebay", "eBay"),
    ("disc", "Discord"),
    ("face", "Facebook"),
    ("inst", "Instagram"),
    ("snap", "Snapchat"),
    ("stea", "Steam"),
    ("webs", "Website"),
]



