# ContactList - CTCL 2023
# Generated: June 28, 2023
# Purpose: Dropdown choices
# THIS FILE IS AUTOMATICALLY GENERATED

choices_smp1 = [
    ("", ""),
    ("disc", "Discord"),
    ("ebay", "eBay"),
    ("epic", "Epic Games"),
    ("face", "Facebook"),
    ("gith", "GitHub"),
    ("link", "LinkedIn"),
    ("payp", "PayPal"),
    ("inst", "Instagram"),
    ("redd", "Reddit"),
    ("snap", "Snapchat"),
    ("stea", "Steam"),
    ("twit", "Twitter"),
    ("webs", "Personal Website"),
]

choices_smp2 = [
    ("", ""),
    ("disc", "Discord"),
    ("ebay", "eBay"),
    ("epic", "Epic Games"),
    ("face", "Facebook"),
    ("gith", "GitHub"),
    ("link", "LinkedIn"),
    ("payp", "PayPal"),
    ("inst", "Instagram"),
    ("redd", "Reddit"),
    ("snap", "Snapchat"),
    ("stea", "Steam"),
    ("twit", "Twitter"),
    ("webs", "Personal Website"),
]

choices_smp3 = [
    ("", ""),
    ("disc", "Discord"),
    ("ebay", "eBay"),
    ("epic", "Epic Games"),
    ("face", "Facebook"),
    ("gith", "GitHub"),
    ("link", "LinkedIn"),
    ("payp", "PayPal"),
    ("inst", "Instagram"),
    ("redd", "Reddit"),
    ("snap", "Snapchat"),
    ("stea", "Steam"),
    ("twit", "Twitter"),
    ("webs", "Personal Website"),
]

choices_smp4 = [
    ("", ""),
    ("disc", "Discord"),
    ("ebay", "eBay"),
    ("epic", "Epic Games"),
    ("face", "Facebook"),
    ("gith", "GitHub"),
    ("link", "LinkedIn"),
    ("payp", "PayPal"),
    ("inst", "Instagram"),
    ("redd", "Reddit"),
    ("snap", "Snapchat"),
    ("stea", "Steam"),
    ("twit", "Twitter"),
    ("webs", "Personal Website"),
]

choices_smp5 = [
    ("", ""),
    ("disc", "Discord"),
    ("ebay", "eBay"),
    ("epic", "Epic Games"),
    ("face", "Facebook"),
    ("gith", "GitHub"),
    ("link", "LinkedIn"),
    ("payp", "PayPal"),
    ("inst", "Instagram"),
    ("redd", "Reddit"),
    ("snap", "Snapchat"),
    ("stea", "Steam"),
    ("twit", "Twitter"),
    ("webs", "Personal Website"),
]

choices_smp6 = [
    ("", ""),
    ("disc", "Discord"),
    ("ebay", "eBay"),
    ("epic", "Epic Games"),
    ("face", "Facebook"),
    ("gith", "GitHub"),
    ("link", "LinkedIn"),
    ("payp", "PayPal"),
    ("inst", "Instagram"),
    ("redd", "Reddit"),
    ("snap", "Snapchat"),
    ("stea", "Steam"),
    ("twit", "Twitter"),
    ("webs", "Personal Website"),
]



choices_themes = [
    ("default", "Flat Dark - Default"),
    ("default-light", "Flat Light"),
]



