# ContactList - CTCL 2023
# Generated: June 28, 2023
# Purpose: Django form data
# THIS FILE IS AUTOMATICALLY GENERATED

from django import forms
from . import choices
from .models import ContactItem

class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactItem
        fields = ['name', 'irln', 'nick', 'prns', 'birt', 'loca', 'dtmt', 'mtth', 'seen', 'appe', 'smp1', 'smu1', 'smp2', 'smu2', 'smp3', 'smu3', 'smp4', 'smu4', 'smp5', 'smu5', 'smp6', 'smu6', 'ema1', 'ema2', 'ema3', 'ema4', 'nphn', 'empl', 'note']
        labels = {'name': 'Name', 'irln': 'Full Real Name', 'nick': 'Nicknames', 'prns': 'Pronouns', 'birt': 'Birthday', 'loca': 'Location', 'dtmt': 'Date Met', 'mtth': 'Met Through', 'seen': 'Seen in real life?', 'appe': 'Appearance', 'smp1': 'Social Media Platform 1', 'smu1': 'Social Media Username 1', 'smp2': 'Social Media Platform 2', 'smu2': 'Social Media Username 2', 'smp3': 'Social Media Platform 3', 'smu3': 'Social Media Username 3', 'smp4': 'Social Media Platform 4', 'smu4': 'Social Media Username 4', 'smp5': 'Social Media Platform 5', 'smu5': 'Social Media Username 5', 'smp6': 'Social Media Platform 6', 'smu6': 'Social Media Username 6', 'ema1': 'Email 1', 'ema2': 'Email 2', 'ema3': 'Email 3', 'ema4': 'Email 4', 'nphn': 'Phone Number', 'empl': 'Employment Information', 'note': 'Notes'}

class SettingsForm(forms.Form):
    theme = forms.CharField(label = "Theme Selection", widget = forms.Select(choices = choices.choices_themes))

