# ContactList - CTCL 2023
# Generated: June 15, 2023
# Purpose: Django form data
# THIS FILE IS AUTOMATICALLY GENERATED

from django import forms
from . import choices

class ContactForm(forms.Form):
    name = forms.CharField(label = "Name", min_length = 1, max_length = 128, required = True)
    irln = forms.CharField(label = "Full Name", min_length = 0, max_length = 128, required = False)
    loca = forms.CharField(label = "Location", min_length = 0, max_length = 128, required = False)
    smp1 = forms.ChoiceField(label = "Social Platform 1", choices = choices.choices_smp1, required = False)
    smu1 = forms.CharField(label = "Social Username 1", min_length = 0, max_length = 64, required = False)
    smp2 = forms.ChoiceField(label = "Social Platform 2", choices = choices.choices_smp2, required = False)
    smu2 = forms.CharField(label = "Social Username 2", min_length = 0, max_length = 64, required = False)
    smp3 = forms.ChoiceField(label = "Social Platform 3", choices = choices.choices_smp3, required = False)
    smu3 = forms.CharField(label = "Social Username 3", min_length = 0, max_length = 64, required = False)
    smp4 = forms.ChoiceField(label = "Social Platform 4", choices = choices.choices_smp4, required = False)
    smu4 = forms.CharField(label = "Social Username 4", min_length = 0, max_length = 64, required = False)
    nte = forms.CharField(label = "Notes", widget = forms.Textarea, required = False)
    dmt = forms.CharField(label = "Date Met", min_length = 0, max_length = 64, required = False)


