# ContactList - CTCL 2023
# Generated: June 16, 2023
# Purpose: HTML table config
# THIS FILE IS AUTOMATICALLY GENERATED

htmltable = [{'name': {'name': 'Name', 'width': '20'}}, {'irln': {'name': 'Full Name', 'width': '20'}}, {'tcrd': {'name': 'Created', 'width': '20'}}, {'tmod': {'name': 'Modified', 'width': '20'}}]

