# ContactList - CTCL 2023
# Generated: June 15, 2023
# Purpose: HTML table config
# THIS FILE IS AUTOMATICALLY GENERATED

htmltable = [{'name': 'Name'}, {'irln': 'Full Name'}, {'crd': 'Created'}, {'mod': 'Modified'}]

